language: python
python: 3.5
# Ubuntu 16.04 (14.04 doesn't have FFmpeg but avconv)
dist: xenial
# Command to install apt dependencies
addons:
  apt:
    packages:
    - ffmpeg
# Command to install Python dependencies
install:
  - pip install -r requirements.txt
# Command to run tests
script:
  - python3 -m unittest discover --start-directory ./tests -v
